# Generated by Django 2.1.7 on 2019-02-14 03:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [('accounts', '0001_initial'), ('core', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                (
                    'price',
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ('image', models.ImageField(upload_to='')),
                ('has_dairy', models.BooleanField(default=False)),
                ('has_nuts', models.BooleanField(default=False)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_halal', models.BooleanField(default=False)),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='food_items',
                        to='core.FoodCategory',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                (
                    'franchise_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_acc_name', models.CharField(max_length=255)),
                ('bank_acc_number', models.CharField(max_length=255)),
                ('transaction_fee_rate', models.PositiveIntegerField(default=0)),
                ('sales_service_tax', models.PositiveIntegerField(default=0)),
                ('service_charge_rate', models.PositiveIntegerField(default=0)),
                ('has_dine_in_service_charge', models.BooleanField(default=False)),
                ('has_takeaway_service_charge', models.BooleanField(default=False)),
                (
                    'rating',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ('is_online', models.BooleanField(default=False)),
                ('search_position', models.PositiveIntegerField(default=1000)),
                ('pax', models.PositiveIntegerField(default=0)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='accounts.RestaurantOwner',
                    ),
                ),
                (
                    'staff',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='accounts.RestaurantStaff',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='food_items',
                to='restaurants.Restaurant',
            ),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='tags',
            field=models.ManyToManyField(
                db_index=True, related_name='food_items', to='core.Tag'
            ),
        ),
    ]
