# Generated by Django 2.1.7 on 2019-03-01 17:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20190225_1557'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('has_dairy', models.BooleanField(default=False)),
                ('has_nuts', models.BooleanField(default=False)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_halal', models.BooleanField(default=False)),
                ('is_non_halal', models.BooleanField(default=False)),
                ('unlimited_addons_required', models.BooleanField(default=False)),
                ('limited_addons_required', models.BooleanField(default=False)),
                ('single_addons_required', models.BooleanField(default=False)),
                ('max_limited_addons', models.PositiveIntegerField(default=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='core.FoodCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodItemAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Unlimited', 'Unlimited'), ('Limited', 'Limited'), ('Single', 'Single')], default='Unlimited', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('required', models.BooleanField(default=False)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='restaurants.FoodItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField(choices=[(0, 'Self Service'), (1, 'Full Service')], default=1)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('franchise_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_acc_name', models.CharField(max_length=255)),
                ('bank_acc_number', models.CharField(max_length=255)),
                ('transaction_fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('sales_service_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('has_dine_in_service_charge', models.BooleanField(default=False)),
                ('has_takeaway_service_charge', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dineout_online', models.BooleanField(default=False)),
                ('takeaway_online', models.BooleanField(default=False)),
                ('search_position', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('seats', models.PositiveIntegerField(default=0)),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('cost_index', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='core.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.RestaurantOwner')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.RestaurantStaff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='tags',
            field=models.ManyToManyField(db_index=True, related_name='food_items', to='core.Tag'),
        ),
    ]
