# Generated by Django 2.1.7 on 2019-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('restaurants', '0001_initial')]

    operations = [
        migrations.RenameField(
            model_name='restaurant', old_name='is_online', new_name='dineout_online'
        ),
        migrations.RenameField(
            model_name='restaurant', old_name='pax', new_name='seats'
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_non_halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cost_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='display_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='takeaway_online',
            field=models.BooleanField(default=False),
        ),
    ]
