# Generated by Django 2.1.7 on 2019-03-01 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190301_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='service_charge_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Service charge rate (%)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='transaction_fee_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Transaction fee rate (%)'),
        ),
    ]
