# Generated by Django 2.1.7 on 2019-03-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20190301_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='friday_closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='friday_opening_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='monday_closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='monday_opening_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_on_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_on_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_on_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_on_sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_on_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_on_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_on_wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='saturday_closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='saturday_opening_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sunday_closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sunday_opening_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thursday_closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thursday_opening_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tuesday_closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tuesday_opening_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wednesday_closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wednesday_opening_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
