# Generated by Django 2.1.7 on 2019-02-21 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20190220_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Self Service'), (1, 'Full Service')], default='Full Service', max_length=20),
        ),
    ]
