# Generated by Django 2.1.7 on 2019-03-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20190302_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='scheduled_closing_dates',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
