# Generated by Django 2.1.7 on 2019-02-23 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20190221_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('required', models.BooleanField(default=False)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='restaurants.FoodItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Self Service'), (1, 'Full Service')], default=1),
        ),
    ]
