# Generated by Django 2.1.7 on 2019-02-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name_plural': 'Food Categories'},
        ),
    ]
