# Generated by Django 2.1.7 on 2019-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190223_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
