# Generated by Django 2.1.7 on 2019-03-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190225_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='state',
            new_name='city',
        ),
        migrations.AddField(
            model_name='location',
            name='town',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
