# Generated by Django 2.1.7 on 2019-02-14 03:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [('accounts', '0001_initial'), ('restaurants', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('BOOKED', 'BOOKED'),
                            ('COMPLETED', 'COMPLETED'),
                            ('CANCELLED', 'CANCELLED'),
                        ],
                        default='BOOKED',
                        max_length=20,
                    ),
                ),
                ('comment', models.TextField()),
                ('is_dine_in', models.BooleanField(default=False)),
                ('pax', models.PositiveIntegerField(default=0)),
                ('scheduled_datetime', models.DateTimeField()),
                (
                    'cancellation_charge',
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    'total',
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ('points_earned', models.PositiveIntegerField(default=0)),
                (
                    'rating',
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ('user_review', models.TextField(blank=True, null=True)),
                ('restaurant_review', models.TextField()),
                (
                    'items',
                    models.ManyToManyField(
                        related_name='orders', to='restaurants.FoodItem'
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='members',
                        to='accounts.Member',
                    ),
                ),
                (
                    'restaurant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='orders',
                        to='restaurants.Restaurant',
                    ),
                ),
            ],
            options={'abstract': False},
        )
    ]
