# Generated by Django 2.1.7 on 2019-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('orders', '0001_initial')]

    operations = [
        migrations.RenameField(model_name='order', old_name='pax', new_name='seats'),
        migrations.RemoveField(model_name='order', name='rating'),
        migrations.AddField(
            model_name='order',
            name='restaurant_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_timing_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant_review',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_review',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
