# Generated by Django 2.1.7 on 2019-03-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_auto_20190301_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='member',
        ),
        migrations.AddField(
            model_name='order',
            name='diner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='diners', to='accounts.Diner'),
            preserve_default=False,
        ),
    ]
