# Generated by Django 2.1.7 on 2019-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20190223_0845'),
        ('orders', '0002_remove_orderitem_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='addons',
            field=models.ManyToManyField(related_name='order_items', to='restaurants.FoodItemAddon'),
        ),
    ]
