# Generated by Django 2.1.7 on 2019-03-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_completed_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_repeat_order',
            field=models.BooleanField(default=False),
        ),
    ]
